language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text